package com.javainuse.classes;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.*;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import javax.persistence.*;
import java.sql.*;
import java.util.Collection;
import java.util.Collections;
import java.util.List;

@Getter
@Setter
@NoArgsConstructor
@EqualsAndHashCode
@Entity
@Table(name = "user")
public class User implements UserDetails {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="userID")
    private Integer userID;
    private String name;
    @Column(name="username")
    private String userName;
    @JsonIgnore
    @Column(name="password")
    private String password;
    @Column(name="email")
    private String email = "user@example.com";
    @Column(name="bio")
    private String bio;
    @Column(name="fav_band")
    private String favBand;
    @Column(name="fav_song")
    private String favSong;
    @JsonIgnore
    @Column(name="locked_until")
    private Timestamp LockedUntil;
    @JsonIgnore
    @Column(name="locked")
    private Boolean locked;
    @JsonIgnore
    @Column(name="invalid_tries")
    private Integer InvalidTries;

//    @JsonBackReference
//    @OneToMany
//    private List<Post> posts;
    @Enumerated(EnumType.STRING)
    @JsonIgnore
    @Transient
    private UserAuthorities userAuthorities = UserAuthorities.USER;
    @JsonIgnore
    @Transient
    private Boolean enabled = true;
    //steven

    //A constructor that takes in all fields besides ID, which is autogenerated. We can add more constructors
    //based on what we need from the registration method

    @JsonIgnore
    public User(String name, String userName, String password, String email, String bio, String favBand,
                String favSong, UserAuthorities userAuthorities, Boolean locked, Boolean enabled) {
        this.name = name;
        this.userName = userName;
        this.password = password;
        this.email = email;
        this.bio = bio;
        this.favBand = favBand;
        this.favSong = favSong;
        this.userAuthorities = userAuthorities;
        this.locked = locked;
        this.enabled = enabled;
    }


    @JsonIgnore
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        SimpleGrantedAuthority authority = new SimpleGrantedAuthority(userAuthorities.name());
        return Collections.singletonList(authority);
    }


    @JsonIgnore
    @Override
    public String getPassword() {
        return this.password;
    }


    @JsonIgnore
    @Override
    public String getUsername() {
        return this.userName;
    }

    @JsonIgnore
    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @JsonIgnore
    @Override
    public boolean isAccountNonLocked() {
        return !locked;
    }


    @JsonIgnore
    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @JsonIgnore
    @Override
    public boolean isEnabled() {
        return enabled;
    }

    @JsonIgnore
    public void userFollowTopic(String username, String topic) throws SQLException
    {
        int userID = getUserIDByUsername(username);
        int topicID = getTopicIDByTopic(topic);

        String dbURL = "jdbc:mysql://localhost:3306/cs307group27?useSSL=false";
        String dbUsername = "Group27";
        String dbPassword = "Pcs307g#27";

        PreparedStatement pstmt = null;
        String query = "INSERT INTO topicfollower(topicID, userID) VALUES(?, ?);";
        try (Connection conn = DriverManager.getConnection(dbURL, dbUsername, dbPassword))
        {
            pstmt = conn.prepareStatement(query);
            pstmt.setInt(1, topicID);
            pstmt.setInt(2, userID);
            pstmt.executeQuery();
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
        finally
        {
            pstmt.close();
        }
    }

    @JsonIgnore
    private int getUserIDByUsername(String username) throws SQLException
    {
        String dbURL = "jdbc:mysql://localhost:3306/cs307group27?useSSL=false";
        String dbUsername = "Group27";
        String dbPassword = "Pcs307g#27";

        PreparedStatement pstmt = null;
        int userID = -1;
        String query = "SELECT userID FROM user WHERE username = ?";
        try (Connection conn = DriverManager.getConnection(dbURL, dbUsername, dbPassword))
        {
            pstmt = conn.prepareStatement(query);
            pstmt.setString(1, username);
            ResultSet res = pstmt.executeQuery();
            while(res.next())
            {
                userID = res.getInt("userID");
            }
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
        finally
        {
            pstmt.close();
        }
        return userID;
    }

    //TODO: this method should be moved to the topic class
    @JsonIgnore
    private int getTopicIDByTopic(String topic) throws SQLException
    {
        String dbURL = "jdbc:mysql://localhost:3306/cs307group27?useSSL=false";
        String dbUsername = "Group27";
        String dbPassword = "Pcs307g#27";

        PreparedStatement pstmt = null;
        int topicID = -1;
        String query = "SELECT topicID FROM topic WHERE topicName = ?";
        try (Connection conn = DriverManager.getConnection(dbURL, dbUsername, dbPassword))
        {
            pstmt = conn.prepareStatement(query);
            pstmt.setString(1, topic);
            ResultSet res = pstmt.executeQuery();
            while(res.next())
            {
                topicID = res.getInt("topicID");
            }
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
        finally
        {
            pstmt.close();
        }
        return topicID;
    }

    @Override
    @JsonIgnore
    public String toString() {
        return "User{" +
                "name='" + name + '\'' +
                "username='" + userName + '\'' +
                "email='" + email + '\'' +
                ", bio='" + bio + '\'' +
                ", favBand='" + favBand + '\'' +
                ", favSong='" + favSong + '\'' +
                '}';
    }
}
